import { Platform, StyleSheet } from 'react-native';

export const baseStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F3F5F7',
  },
  header: {
    paddingTop: 40,
    paddingBottom: 24,
    paddingHorizontal: 20,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#0f172a',
    marginBottom: 4,
  },
  headerSubtitle: {
    fontSize: 13,
    color: '#64748b',
  },
  content: {
    flex: 1,
    paddingHorizontal: 20,
  },
  section: {
    backgroundColor: '#ffffff',
    borderRadius: 16,
    padding: 14,
    marginTop: 8,
    shadowColor: '#0f172a',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 3,
    borderWidth: 1,
    borderColor: '#eef2f6',
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  calculateButton: {
    borderRadius: 8,
    overflow: 'hidden',
  },
  calculateButtonGradient: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 8,
  },
  calculateButtonText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '600',
  },
  pricePlaceholder: {
    alignItems: 'center',
    paddingVertical: 24,
  },
  pricePlaceholderText: {
    fontSize: 16,
    color: '#64748b',
    fontWeight: '500',
    marginBottom: 8,
  },
  pricePlaceholderSubtext: {
    fontSize: 14,
    color: '#94a3b8',
    textAlign: 'center',
  },
  sectionTitleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: '#1e293b',
  },
  switchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    padding: 2,
  },
  switchLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: '#64748b',
  },
  inputGroup: {
    marginBottom: 10,
  },
  label: {
    fontSize: 13,
    fontWeight: '600',
    color: '#475569',
    marginBottom: 5,
  },
  labelRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  linkButton: {
    fontSize: 13,
    color: '#2C98A6',
    fontWeight: '600',
  },
  input: {
    backgroundColor: '#f8fafc',
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 14,
    color: '#1e293b',
  },
  textArea: {
    minHeight: 68,
    textAlignVertical: 'top',
  },
  coordsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 8,
    backgroundColor: '#f0fdf4',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    borderLeftWidth: 3,
    borderLeftColor: '#059669',
  },
  coordsLabel: {
    fontSize: 12,
    color: '#059669',
    fontWeight: '600',
    marginRight: 4,
  },
  coordsText: {
    fontSize: 12,
    color: '#059669',
    fontWeight: '500',
  },
  coordinateInfo: {
    marginTop: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: '#f0f9ff',
    borderRadius: 8,
    borderLeftWidth: 3,
    borderLeftColor: '#2C98A6',
  },
  coordinateText: {
    fontSize: 12,
    color: '#1F7A86',
    fontWeight: '500',
  },
  chipContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  chip: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    backgroundColor: '#f8fafc',
  },
  chipActive: {
    backgroundColor: '#2C98A6',
    borderColor: '#2C98A6',
  },
  chipText: {
    fontSize: 14,
    color: '#64748b',
    fontWeight: '500',
  },
  chipTextActive: {
    color: '#fff',
    fontWeight: '600',
  },
  radioOption: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 14,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    backgroundColor: '#f8fafc',
    marginBottom: 10,
  },
  radioOptionActive: {
    backgroundColor: '#e8f5f6',
    borderColor: '#2C98A6',
  },
  radio: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: '#cbd5e1',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  radioInner: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#2C98A6',
  },
  radioContent: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  radioText: {
    fontSize: 15,
    color: '#475569',
  },
  radioTextActive: {
    color: '#1F7A86',
    fontWeight: '600',
  },
  extraPrice: {
    fontSize: 13,
    color: '#f59e0b',
    fontWeight: '600',
  },
  priceCard: {
    backgroundColor: '#f8fafc',
    borderRadius: 12,
    padding: 16,
  },
  priceRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  priceLabel: {
    fontSize: 14,
    color: '#64748b',
  },
  priceValue: {
    fontSize: 14,
    color: '#1e293b',
    fontWeight: '500',
  },
  priceDivider: {
    height: 1,
    backgroundColor: '#e2e8f0',
    marginVertical: 8,
  },
  priceLabelTotal: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#1e293b',
  },
  priceTotal: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#2C98A6',
  },
  submitButton: {
    marginTop: 32,
    marginBottom: 20,
    borderRadius: 20,
    overflow: 'hidden',
    shadowColor: '#2C98A6',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.4,
    shadowRadius: 16,
    elevation: 10,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
  },
  submitButtonDisabled: {
    opacity: 0.7,
  },
  submitGradient: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 20,
    paddingHorizontal: 24,
    gap: 12,
  },
  submitText: {
    fontSize: 20,
    fontWeight: '800',
    color: '#ffffff',
    letterSpacing: 1,
  },
  qrModalClose: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#e8edf2',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 10,
  },
  qrModalCloseText: {
    fontSize: 18,
    color: '#1A2B48',
    fontWeight: 'bold',
  },
  submitPrice: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#ffffff',
  },
  // 地图模态框样式
  mapModalContainer: {
    flex: 1,
    backgroundColor: '#ffffff',
  },
  mapHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: Platform.OS === 'ios' ? 50 : 30,
    paddingBottom: 15,
    backgroundColor: '#ffffff',
    borderBottomWidth: 1,
    borderBottomColor: '#e2e8f0',
  },
  mapCloseButton: {
    fontSize: 28,
    color: '#64748b',
    fontWeight: 'bold',
    width: 40,
  },
  mapTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#1e293b',
    flex: 1,
    textAlign: 'center',
  },
  mapHeaderButtons: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  mapCurrentLocationButton: {
    backgroundColor: '#f0f9ff',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#2C98A6',
  },
  mapCurrentLocationText: {
    fontSize: 14,
    color: '#2C98A6',
    fontWeight: '600',
  },
  mapConfirmButton: {
    fontSize: 28,
    color: '#2C98A6',
    fontWeight: 'bold',
    width: 40,
    textAlign: 'right',
  },
  map: {
    flex: 1,
    width: '100%',
    height: '100%',
  },
  mapFooter: {
    backgroundColor: '#ffffff',
    paddingVertical: 20,
    paddingHorizontal: 20,
    borderTopWidth: 1,
    borderTopColor: '#e2e8f0',
  },
  mapInstructions: {
    fontSize: 14,
    color: '#64748b',
    textAlign: 'center',
  },
  mapAddressInputContainer: {
    paddingHorizontal: 20,
    paddingVertical: 15,
    backgroundColor: '#ffffff',
    borderTopWidth: 1,
    borderTopColor: '#e2e8f0',
    position: 'relative',
    zIndex: 1000,
  },
  mapAddressInput: {
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 8,
    paddingHorizontal: 15,
    paddingVertical: 12,
    fontSize: 16,
    color: '#1e293b',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  suggestionsContainer: {
    position: 'absolute',
    top: 70, // 输入框下方 (padding 15 + input height ~50 + margin 5)
    left: 20,
    right: 20,
    backgroundColor: '#ffffff',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    maxHeight: 300,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 8,
    zIndex: 1001,
  },
  suggestionsList: {
    maxHeight: 400,
  },
  suggestionItem: {
    paddingHorizontal: 16,
    paddingVertical: 14,
    backgroundColor: '#ffffff',
    flexDirection: 'row',
    alignItems: 'center',
  },
  suggestionItemBorder: {
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
  },
  suggestionIcon: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#f3f4f6',
    justifyContent: 'center',
    alignItems: 'center',
  },
  suggestionMainText: {
    fontSize: 16,
    fontWeight: '400',
    color: '#1f2937',
    flex: 1,
  },
  suggestionSecondaryText: {
    fontSize: 14,
    color: '#6b7280',
    marginTop: 4,
  },
  loadingIndicator: {
    position: 'absolute',
    right: 12,
    top: 12,
    backgroundColor: '#ffffff',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 4,
  },
  loadingText: {
    fontSize: 12,
    color: '#6b7280',
  },
  loadingContainer: {
    padding: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  noResultsContainer: {
    padding: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  noResultsText: {
    fontSize: 14,
    color: '#9ca3af',
    textAlign: 'center',
  },
  // 包裹类型说明模态框样式
  infoModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  infoModalContent: {
    width: '90%',
    maxWidth: 400,
  },
  infoModalCard: {
    backgroundColor: '#ffffff',
    borderRadius: 20,
    padding: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.3,
    shadowRadius: 20,
    elevation: 10,
  },
  infoModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  infoModalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#1e293b',
  },
  infoModalClose: {
    fontSize: 24,
    color: '#94a3b8',
    fontWeight: 'bold',
  },
  infoModalBody: {
    marginBottom: 24,
  },
  infoItem: {
    marginBottom: 16,
  },
  infoLabel: {
    fontSize: 15,
    fontWeight: '600',
    color: '#475569',
    marginBottom: 6,
  },
  infoValue: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#2C98A6',
    marginBottom: 4,
  },
  infoDescription: {
    fontSize: 14,
    color: '#64748b',
    lineHeight: 20,
  },
  infoModalButton: {
    borderRadius: 12,
    overflow: 'hidden',
    shadowColor: '#2C98A6',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  infoModalButtonGradient: {
    paddingVertical: 14,
    alignItems: 'center',
  },
  infoModalButtonText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#ffffff',
  },
  // QR码模态框样式（对齐确认订单页：浅底、白卡、海军蓝标题、青绿主按钮）
  qrModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(26, 43, 72, 0.45)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 16,
  },
  qrModalContent: {
    backgroundColor: '#F5F7FA',
    borderRadius: 20,
    width: '100%',
    maxWidth: 400,
    overflow: 'hidden',
    shadowColor: '#1A2B48',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.18,
    shadowRadius: 24,
    elevation: 16,
  },
  qrModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: 12,
    backgroundColor: '#ffffff',
    borderBottomWidth: 1,
    borderBottomColor: '#eef2f6',
  },
  qrModalHeaderSpacer: {
    width: 36,
  },
  qrModalTitle: {
    flex: 1,
    textAlign: 'center',
    fontSize: 17,
    fontWeight: '800',
    color: '#1A2B48',
  },
  qrShot: {
    backgroundColor: '#F5F7FA',
  },
  qrModalBody: {
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 8,
  },
  qrCard: {
    backgroundColor: '#ffffff',
    borderRadius: 16,
    padding: 18,
    alignItems: 'center',
    shadowColor: '#1A2B48',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 10,
    elevation: 3,
    borderWidth: 1,
    borderColor: '#eef2f6',
  },
  qrSuccessBadge: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#2C98A6',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 10,
  },
  qrSuccessText: {
    fontSize: 15,
    fontWeight: '800',
    color: '#2C98A6',
    marginBottom: 16,
  },
  qrInfoText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#8A94A6',
    marginTop: 4,
    marginBottom: 4,
  },
  qrOrderId: {
    fontSize: 16,
    fontWeight: '800',
    color: '#1A2B48',
    marginBottom: 4,
    letterSpacing: 0.2,
  },
  qrPaidRow: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 14,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#eef2f6',
  },
  qrPaidLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: '#8A94A6',
  },
  qrOrderPrice: {
    fontSize: 20,
    fontWeight: '800',
    color: '#2C98A6',
  },
  qrCodeContainer: {
    marginBottom: 14,
    alignItems: 'center',
  },
  qrCodeWrapper: {
    padding: 14,
    backgroundColor: '#ffffff',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#e8edf2',
  },
  qrTicketRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    marginTop: 4,
    marginBottom: 12,
    gap: 3,
  },
  qrTicketDashSeg: {
    width: 8,
    height: 2,
    borderRadius: 1,
  },
  qrHint: {
    fontSize: 13,
    lineHeight: 18,
    color: '#8A94A6',
    textAlign: 'center',
    paddingHorizontal: 8,
  },
  qrBreakdownCard: {
    marginTop: 10,
    backgroundColor: '#ffffff',
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 14,
    shadowColor: '#1A2B48',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 10,
    elevation: 3,
    borderWidth: 1,
    borderColor: '#eef2f6',
  },
  qrBreakdownRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 6,
  },
  qrBreakdownLabel: {
    fontSize: 14,
    color: '#64748b',
    fontWeight: '500',
  },
  qrBreakdownValue: {
    fontSize: 14,
    fontWeight: '600',
    color: '#334155',
  },
  qrBreakdownCoupon: {
    color: '#22C55E',
    fontWeight: '700',
  },
  qrBreakdownDivider: {
    height: 1,
    backgroundColor: '#eef2f6',
    marginVertical: 8,
  },
  qrBreakdownTotalLabel: {
    fontSize: 15,
    fontWeight: '800',
    color: '#1A2B48',
  },
  qrBreakdownTotalValue: {
    fontSize: 20,
    fontWeight: '800',
    color: '#2C98A6',
  },
  qrRemarkCard: {
    marginTop: 10,
    backgroundColor: '#ffffff',
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 14,
    shadowColor: '#1A2B48',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 10,
    elevation: 3,
    borderWidth: 1,
    borderColor: '#eef2f6',
  },
  qrRemarkTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: '#334155',
    marginBottom: 6,
  },
  qrRemarkText: {
    fontSize: 13,
    color: '#8A94A6',
    lineHeight: 18,
  },
  qrModalFooter: {
    backgroundColor: '#ffffff',
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 16,
    borderTopWidth: 1,
    borderTopColor: '#eef2f6',
    gap: 12,
  },
  qrSecondaryBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#d5dde6',
  },
  qrSecondaryBtnText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#2C98A6',
  },
  qrActionBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  qrActionBarSide: {
    flex: 1,
    minWidth: 0,
  },
  qrPayableLabel: {
    fontSize: 12,
    color: '#8A94A6',
    fontWeight: '600',
    marginBottom: 2,
  },
  qrPayableValue: {
    fontSize: 20,
    fontWeight: '800',
    color: '#2C98A6',
  },
  qrPrimaryBtn: {
    borderRadius: 24,
    backgroundColor: '#2C98A6',
    minWidth: 128,
    paddingVertical: 14,
    paddingHorizontal: 22,
    alignItems: 'center',
    justifyContent: 'center',
  },
  qrPrimaryBtnText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '800',
  },
  // 支付方式选择样式
  paymentMethodContainer: {
    marginTop: 12,
  },
  paymentMethodOption: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    marginBottom: 12,
    backgroundColor: '#f8fafc',
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#e2e8f0',
  },
  paymentMethodOptionActive: {
    backgroundColor: '#f0f9ff',
    borderColor: '#2C98A6',
  },
  paymentMethodRadio: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#94a3b8',
    marginRight: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  paymentMethodRadioInner: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: '#2C98A6',
  },
  paymentMethodContent: {
    flex: 1,
  },
  paymentMethodLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: '#475569',
    marginBottom: 4,
  },
  paymentMethodLabelActive: {
    color: '#2C98A6',
  },
  paymentMethodDesc: {
    fontSize: 13,
    color: '#64748b',
  },
  // 时间选择器样式
  timePickerOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  timePickerContent: {
    backgroundColor: '#ffffff',
    borderRadius: 24,
    width: '92%',
    maxWidth: 400,
    maxHeight: '85%',
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 16,
    elevation: 16,
  },
  timePickerHeader: {
    paddingVertical: 18,
    paddingHorizontal: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  timePickerHeaderContent: {
    flex: 1,
  },
  timePickerTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#ffffff',
    marginBottom: 2,
  },
  timePickerSubtitle: {
    fontSize: 12,
    color: 'rgba(255, 255, 255, 0.9)',
  },
  timePickerCloseButton: {
    width: 30,
    height: 32,
    borderRadius: 15,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  timePickerBody: {
    padding: 20,
  },
  quickSelectSection: {
    marginBottom: 20,
  },
  quickSelectTitle: {
    fontSize: 15,
    fontWeight: 'bold',
    color: '#1e293b',
  },
  quickSelectGrid: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 12,
  },
  quickSelectButton: {
    flex: 1,
    backgroundColor: '#f8fafc',
    borderWidth: 1.5,
    borderColor: '#e2e8f0',
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  quickSelectButtonText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#64748b',
  },
  timeSlotsSection: {
    height: 220, // 固定高度防止重叠
  },
  timeSlotsTitle: {
    fontSize: 15,
    fontWeight: 'bold',
    color: '#1e293b',
  },
  timeSlotsContainer: {
    marginTop: 8,
    flex: 1,
  },
  timeSlotsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    justifyContent: 'flex-start',
    paddingBottom: 10,
  },
  timeSlotButton: {
    width: '31.3%', // 精确计算宽度
    backgroundColor: '#f8fafc',
    borderWidth: 1.5,
    borderColor: '#e2e8f0',
    borderRadius: 10,
    paddingVertical: 10,
    alignItems: 'center',
    marginBottom: 2,
  },
  timeSlotButtonActive: {
    borderColor: '#2C98A6',
    backgroundColor: '#e8f5f6',
  },
  timeSlotText: {
    fontSize: 13,
    color: '#64748b',
    fontWeight: '700',
  },
  timeSlotTextActive: {
    color: '#2C98A6',
  },
  timePickerButtons: {
    flexDirection: 'row',
    gap: 12,
    padding: 20,
    borderTopWidth: 1,
    borderTopColor: '#f1f5f9',
    backgroundColor: '#fff',
  },
  timePickerCancelButton: {
    flex: 1,
    backgroundColor: '#f1f5f9',
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  timePickerCancelText: {
    fontSize: 15,
    fontWeight: '700',
    color: '#64748b',
  },
  timePickerConfirmButton: {
    flex: 2,
    borderRadius: 12,
    overflow: 'hidden',
  },
  timePickerConfirmGradient: {
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 6,
  },
  timePickerConfirmText: {
    fontSize: 15,
    fontWeight: 'bold',
    color: '#ffffff',
  },
  // 选中POI信息样式
  selectedPlaceInfo: {
    backgroundColor: '#f0f9ff',
    borderRadius: 8,
    padding: 12,
    marginTop: 8,
    borderWidth: 1,
    borderColor: '#0ea5e9',
  },
  selectedPlaceName: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#0c4a6e',
    marginBottom: 4,
  },
  selectedPlaceAddress: {
    fontSize: 12,
    color: '#0369a1',
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    width: '90%',
    maxWidth: 400,
    backgroundColor: '#ffffff',
    borderRadius: 20,
    padding: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.3,
    shadowRadius: 20,
    elevation: 10,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#1e293b',
    marginBottom: 16,
  },
  modalText: {
    fontSize: 15,
    color: '#475569',
    lineHeight: 24,
    marginBottom: 24,
  },
  modalCloseButton: {
    backgroundColor: '#2C98A6',
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: 'center',
    marginTop: 16,
  },
  modalCloseButtonText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#ffffff',
  },
  // 商家商品选择样式
  selectProductBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
    backgroundColor: '#eff6ff',
    borderWidth: 1,
    borderColor: '#dbeafe',
  },
  selectProductBtnText: {
    fontSize: 12,
    color: '#2C98A6',
    fontWeight: '600',
  },
  selectedProductsList: {
    backgroundColor: '#f8fafc',
    borderRadius: 12,
    padding: 12,
    marginBottom: 15,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  selectedProductItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
  },
  selectedProductName: {
    flex: 1,
    fontSize: 14,
    color: '#1e293b',
    fontWeight: '500',
  },
  qtyControl: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginHorizontal: 12,
  },
  qtyText: {
    fontSize: 15,
    fontWeight: 'bold',
    color: '#1e293b',
    minWidth: 20,
    textAlign: 'center',
  },
  selectedProductPrice: {
    fontSize: 13,
    color: '#10b981',
    fontWeight: '700',
    minWidth: 80,
    textAlign: 'right',
  },
  productTotalRow: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
    gap: 8,
    marginTop: 10,
    paddingTop: 8,
  },
  productTotalLabel: {
    fontSize: 13,
    color: '#64748b',
    fontWeight: '600',
  },
  productTotalValue: {
    fontSize: 16,
    color: '#2C98A6',
    fontWeight: 'bold',
  },
  selectorItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 12,
    backgroundColor: '#f8fafc',
    borderRadius: 12,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  selectorImageContainer: {
    width: 48,
    height: 48,
    borderRadius: 8,
    backgroundColor: '#fff',
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
  },
  selectorImage: {
    width: '100%',
    height: '100%',
  },
  selectorRightContent: {
    flex: 1,
    marginLeft: 12,
    justifyContent: 'space-between',
    paddingVertical: 2,
  },
  selectorName: {
    fontSize: 15,
    fontWeight: 'bold',
    color: '#1e293b',
    marginBottom: 2,
  },
  selectorPrice: {
    fontSize: 14,
    color: '#10b981',
    fontWeight: 'bold',
    marginBottom: 4,
  },
  selectorBottomRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 2,
  },
  selectorStockRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  selectorStockText: {
    fontSize: 11,
    color: '#94a3b8',
    fontWeight: '500',
  },
  selectorQtyControl: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  modalConfirmBtn: {
    borderRadius: 12,
    overflow: 'hidden',
    marginTop: 10,
  },
  modalConfirmGradient: {
    paddingVertical: 14,
    alignItems: 'center',
  },
  modalConfirmText: {
    color: 'white',
    fontSize: 16,
    fontWeight: 'bold',
  },
  modalCloseBtn: {
    padding: 4,
  },
  // 代收切换样式
  codToggleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  codToggleLabel: {
    fontSize: 13,
    color: '#94a3b8',
    fontWeight: '600',
  },
  codToggleLabelActive: {
    color: '#2C98A6',
  },
});

export const wizardStyles = StyleSheet.create({
  mainColumn: {
    flex: 1,
  },
  bottomBar: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    paddingHorizontal: 16,
    paddingTop: 12,
    backgroundColor: '#ffffff',
    borderTopWidth: 1,
    borderTopColor: '#eef2f6',
  },
  guestBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#e8f5f6',
    borderWidth: 1,
    borderColor: 'rgba(44, 152, 166, 0.28)',
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 10,
    marginBottom: 14,
  },
  guestBannerText: {
    flex: 1,
    color: '#1F7A86',
    fontSize: 13,
    fontWeight: '600',
    marginRight: 8,
  },
  guestBannerLink: {
    color: '#2C98A6',
    fontSize: 13,
    fontWeight: '800',
  },
  topChrome: {
    paddingHorizontal: 12,
    zIndex: 2,
    backgroundColor: '#F3F5F7',
  },
  topChromeCompact: {
    paddingBottom: 0,
  },
  navRow: {
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: 44,
    marginBottom: 8,
  },
  navBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#e8edf2',
  },
  navTitle: {
    flex: 1,
    textAlign: 'center',
    fontSize: 17,
    fontWeight: '800',
    color: '#0f172a',
  },
  navSide: {
    width: 36,
  },
  actionBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  actionBarSide: {
    flex: 1,
    minHeight: 40,
    justifyContent: 'center',
  },
  actionBarSideEnd: {
    alignItems: 'flex-end',
    flex: 0,
  },
  payableLabel: {
    fontSize: 12,
    color: '#64748b',
    fontWeight: '600',
    marginBottom: 2,
  },
  payableValue: {
    fontSize: 20,
    fontWeight: '800',
    color: '#2C98A6',
  },
  actionPrimaryBtn: {
    borderRadius: 24,
    overflow: 'hidden',
    minWidth: 128,
    maxWidth: '100%',
  },
  actionPrimaryGradient: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 14,
    paddingHorizontal: 22,
    backgroundColor: '#2C98A6',
    borderRadius: 24,
  },
  nextBtnText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '800',
    flexShrink: 1,
  },
});
