import { Dimensions, Platform, StyleSheet } from 'react-native';

const { width, height } = Dimensions.get('window');
export const TEAL = '#2C98A6';
export const PAGE_BG = '#F3F5F7';
export const NAVY = '#0f172a';
export const MAP_HERO = Math.round(height * 0.42);

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: PAGE_BG,
  },
  header: {
    paddingTop: 60,
    paddingBottom: 30,
    paddingHorizontal: 20,
    borderBottomLeftRadius: 30,
    borderBottomRightRadius: 30,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 8,
  },
  headerTitle: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#ffffff',
    marginBottom: 8,
  },
  headerSubtitle: {
    fontSize: 16,
    color: 'rgba(255, 255, 255, 0.9)',
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    padding: 20,
  },
  searchContainer: {
    marginBottom: 24,
    gap: 12,
  },
  searchInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderRadius: 12,
    paddingHorizontal: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
  },
  searchIcon: {
    fontSize: 18,
    marginRight: 12,
  },
  searchInput: {
    flex: 1,
    fontSize: 16,
    color: '#1e293b',
    paddingVertical: 16,
  },
  trackButton: {
    borderRadius: 12,
    overflow: 'hidden',
    shadowColor: '#2C98A6',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  trackButtonGradient: {
    paddingVertical: 16,
    alignItems: 'center',
  },
  trackButtonText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#ffffff',
  },
  loadingContainer: {
    alignItems: 'center',
    paddingVertical: 60,
  },
  loadingText: {
    marginTop: 12,
    fontSize: 16,
    color: '#64748b',
  },
  notFoundContainer: {
    alignItems: 'center',
    paddingVertical: 60,
    paddingHorizontal: 40,
  },
  notFoundIcon: {
    fontSize: 78,
    marginBottom: 20,
  },
  notFoundText: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#1e293b',
    marginBottom: 8,
  },
  notFoundDesc: {
    fontSize: 16,
    color: '#64748b',
    textAlign: 'center',
  },
  statusCard: {
    marginBottom: 24,
    borderRadius: 24,
    overflow: 'hidden',
    shadowColor: '#1F7A84',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.2,
    shadowRadius: 24,
    elevation: 10,
  },
  statusGradient: {
    padding: 30,
    alignItems: 'center',
  },
  statusHeader: {
    alignItems: 'center',
  },
  statusBadge: {
    fontSize: 13,
    fontWeight: '700',
    color: 'rgba(255, 255, 255, 0.85)',
    marginBottom: 8,
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 999,
    overflow: 'hidden',
    backgroundColor: 'rgba(255, 255, 255, 0.18)',
  },
  etaContainer: {
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 15,
    marginBottom: 15,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.3)',
  },
  etaLabel: {
    color: 'rgba(255, 255, 255, 0.8)',
    fontSize: 12,
    fontWeight: 'bold',
    textTransform: 'uppercase',
    marginBottom: 2,
  },
  etaValue: {
    color: '#ffffff',
    fontSize: 28,
    fontWeight: '900',
  },
  statusIcon: {
    fontSize: 58,
    marginBottom: 16,
  },
  statusText: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#ffffff',
    marginBottom: 8,
  },
  statusTime: {
    fontSize: 14,
    color: 'rgba(255, 255, 255, 0.9)',
  },
  card: {
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    borderRadius: 20,
    padding: 20,
    marginBottom: 16,
    shadowColor: '#1F7A84',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.1,
    shadowRadius: 20,
    elevation: 5,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.8)',
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#1e293b',
    marginBottom: 16,
  },
  infoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
  },
  infoLabel: {
    fontSize: 14,
    color: '#64748b',
    flex: 1,
  },
  infoValue: {
    fontSize: 14,
    fontWeight: '600',
    color: '#1e293b',
    flex: 2,
    textAlign: 'right',
  },
  infoPriceValue: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#2C98A6',
    flex: 2,
    textAlign: 'right',
  },
  addressContainer: {
    backgroundColor: '#f8fafc',
    padding: 16,
    borderRadius: 12,
  },
  addressRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  addressName: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#1e293b',
  },
  addressPhone: {
    fontSize: 13,
    color: '#1E6F7A',
    fontWeight: '600',
  },
  addressText: {
    fontSize: 14,
    color: '#64748b',
    lineHeight: 20,
  },
  trackingItem: {
    flexDirection: 'row',
    marginBottom: 20,
  },
  trackingDot: {
    width: 40,
    alignItems: 'center',
  },
  trackingDotInner: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: '#cbd5e1',
    borderWidth: 2,
    borderColor: '#ffffff',
  },
  trackingDotActive: {
    backgroundColor: '#2C98A6',
    width: 16,
    height: 16,
    borderRadius: 8,
  },
  trackingLine: {
    width: 2,
    flex: 1,
    backgroundColor: '#e2e8f0',
    marginTop: 4,
  },
  trackingContent: {
    flex: 1,
    paddingLeft: 12,
  },
  trackingStatus: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#1e293b',
    marginBottom: 4,
  },
  trackingNote: {
    fontSize: 14,
    color: '#64748b',
    marginBottom: 4,
  },
  trackingTime: {
    fontSize: 12,
    color: '#94a3b8',
  },
  mapContainer: {
    height: 300,
    width: '100%',
    borderRadius: 24,
    overflow: 'hidden',
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 10,
    elevation: 5,
  },
  map: {
    flex: 1,
  },
  mapFallback: {
    flex: 1,
    backgroundColor: '#0f172a',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 24,
  },
  mapFallbackIcon: {
    fontSize: 36,
    marginBottom: 8,
  },
  mapFallbackTitle: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 6,
    textAlign: 'center',
  },
  mapFallbackDesc: {
    color: '#cbd5e1',
    fontSize: 13,
    textAlign: 'center',
    lineHeight: 18,
  },
  riderMarker: {
    backgroundColor: 'white',
    padding: 5,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: '#2C98A6',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  mapOverlay: {
    position: 'absolute',
    bottom: 12,
    left: 12,
    right: 12,
    backgroundColor: 'rgba(30, 58, 138, 0.85)',
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 12,
  },
  mapOverlayText: {
    color: 'white',
    fontSize: 12,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  darkContainer: {
    backgroundColor: '#0f172a',
  },
  darkCard: {
    backgroundColor: '#1e293b',
    borderColor: '#334155',
  },
  darkText: {
    color: '#f8fafc',
  },
  darkInfoRow: {
    borderBottomColor: '#334155',
  },
  darkAddressContainer: {
    backgroundColor: '#0f172a',
  },
  darkSearchInput: {
    backgroundColor: '#1e293b',
    borderColor: '#334155',
  },
  proofImage: {
    width: 120,
    height: 120,
    borderRadius: 12,
    backgroundColor: '#f1f5f9',
  },
  proofTime: {
    fontSize: 10,
    color: '#64748b',
    marginTop: 4,
    textAlign: 'center',
  },
  // 🚀 聊天相关样式
  miniChatBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: 'rgba(59, 130, 246, 0.1)',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
  },
  miniUnreadBadge: {
    position: 'absolute',
    top: -5,
    right: -5,
    backgroundColor: '#ef4444',
    borderRadius: 8,
    minWidth: 16,
    height: 16,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 4,
    borderWidth: 1,
    borderColor: '#fff',
  },
  miniUnreadBadgeText: {
    color: '#fff',
    fontSize: 9,
    fontWeight: 'bold',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-end',
  },
  chatModalContent: {
    height: '80%',
    backgroundColor: '#fff',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    overflow: 'hidden',
  },
  darkChatModal: {
    backgroundColor: '#0f172a',
  },
  chatHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
    backgroundColor: '#fff',
  },
  darkChatHeader: {
    backgroundColor: '#1e293b',
    borderBottomColor: '#334155',
  },
  chatTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#1e293b',
  },
  chatSubtitle: {
    fontSize: 12,
    color: '#94a3b8',
    marginTop: 2,
  },
  chatCloseBtn: {
    padding: 4,
  },
  messageList: {
    flex: 1,
    padding: 16,
    backgroundColor: '#f8fafc',
  },
  darkMessageList: {
    backgroundColor: '#0f172a',
  },
  emptyChat: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 40,
  },
  emptyChatText: {
    color: '#94a3b8',
    fontSize: 14,
  },
  messageWrapper: {
    marginBottom: 16,
    maxWidth: '80%',
  },
  myMessageWrapper: {
    alignSelf: 'flex-end',
  },
  otherMessageWrapper: {
    alignSelf: 'flex-start',
  },
  messageBubble: {
    padding: 12,
    borderRadius: 16,
  },
  myBubble: {
    backgroundColor: TEAL,
    borderBottomRightRadius: 4,
  },
  otherBubble: {
    backgroundColor: '#fff',
    borderBottomLeftRadius: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  darkOtherBubble: {
    backgroundColor: '#1e293b',
  },
  messageText: {
    fontSize: 15,
    lineHeight: 24, // 🚀 增加行高
    paddingVertical: 2, // 🚀 增加垂直边距
  },
  myMessageText: {
    color: '#fff',
  },
  otherMessageText: {
    color: '#1e293b',
  },
  messageTime: {
    fontSize: 10,
    color: '#94a3b8',
    marginTop: 4,
    textAlign: 'right',
  },
  chatInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    paddingBottom: Platform.OS === 'ios' ? 34 : 16,
    backgroundColor: '#fff',
    borderTopWidth: 1,
    borderTopColor: '#f1f5f9',
    gap: 12,
  },
  chatInput: {
    flex: 1,
    backgroundColor: '#f1f5f9',
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 10,
    maxHeight: 100,
    fontSize: 15,
    color: '#1e293b',
  },
  darkChatInput: {
    backgroundColor: '#0f172a',
    color: '#f8fafc',
  },
  sendBtn: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: TEAL,
    justifyContent: 'center',
    alignItems: 'center',
  },
  sendBtnDisabled: {
    backgroundColor: '#e2e8f0',
  },
  offlineBanner: {
    backgroundColor: 'rgba(15, 23, 42, 0.9)',
    borderRadius: 12,
    paddingVertical: 8,
    paddingHorizontal: 12,
    marginTop: 10,
    marginBottom: 6,
  },
  offlineBannerText: {
    color: '#e2e8f0',
    fontSize: 12,
    textAlign: 'center',
  },
  ongoingContainer: {
    marginBottom: 20,
  },
  ongoingTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: NAVY,
    marginBottom: 12,
    paddingHorizontal: 4,
  },
  ongoingCard: {
    width: 200,
    borderRadius: 16,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  ongoingCardGradient: {
    padding: 16,
    height: 100,
    justifyContent: 'space-between',
  },
  ongoingCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  ongoingOrderId: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#1F7A84',
  },
  ongoingBadge: {
    backgroundColor: '#8b5cf6',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 8,
  },
  ongoingBadgeText: {
    color: 'white',
    fontSize: 10,
    fontWeight: 'bold',
  },
  ongoingAddress: {
    fontSize: 12,
    color: '#64748b',
    marginTop: 8,
  },
  ongoingTap: {
    fontSize: 10,
    color: TEAL,
    fontWeight: '600',
    marginTop: 4,
  },
});

export const ui = StyleSheet.create({
  page: {
    flex: 1,
    backgroundColor: PAGE_BG,
  },
  navRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingBottom: 8,
  },
  navRowOverlay: {
    zIndex: 8,
  },
  navBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#e8edf2',
  },
  navTitle: {
    flex: 1,
    textAlign: 'center',
    fontSize: 17,
    fontWeight: '800',
    color: NAVY,
  },
  supportBtn: {
    width: 48,
    alignItems: 'center',
  },
  supportLabel: {
    fontSize: 10,
    fontWeight: '700',
    color: NAVY,
    marginTop: 2,
  },
  browseSubtitle: {
    fontSize: 13,
    color: '#64748b',
    fontWeight: '600',
    marginBottom: 14,
  },
  hero: {
    height: MAP_HERO,
    backgroundColor: '#d8eef1',
    overflow: 'hidden',
  },
  heroScrim: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(255,255,255,0.08)',
  },
  statusFloat: {
    position: 'absolute',
    left: 16,
    bottom: 28,
    maxWidth: width * 0.52,
    backgroundColor: '#fff',
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 12,
    shadowColor: '#0f172a',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.12,
    shadowRadius: 16,
    elevation: 8,
    zIndex: 6,
  },
  statusHeadline: {
    fontSize: 18,
    fontWeight: '800',
    color: NAVY,
    lineHeight: 24,
  },
  statusEta: {
    marginTop: 6,
    fontSize: 13,
    fontWeight: '700',
    color: TEAL,
  },
  riderPin: {
    backgroundColor: '#fff',
    padding: 4,
    borderRadius: 16,
    borderWidth: 2,
    borderColor: TEAL,
  },
  sheet: {
    flex: 1,
    backgroundColor: '#fff',
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    marginTop: -18,
    paddingTop: 16,
    overflow: 'hidden',
    zIndex: 6,
  },
  riderBar: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    gap: 10,
  },
  riderAvatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: TEAL,
    alignItems: 'center',
    justifyContent: 'center',
  },
  riderAvatarText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '800',
  },
  riderName: {
    fontSize: 16,
    fontWeight: '800',
    color: NAVY,
  },
  riderMeta: {
    marginTop: 2,
    fontSize: 12,
    color: '#64748b',
    fontWeight: '600',
  },
  actionCircle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: TEAL,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  actionCol: {
    alignItems: 'center',
    width: 56,
  },
  actionLabel: {
    marginTop: 4,
    fontSize: 10,
    fontWeight: '700',
    color: '#64748b',
    textAlign: 'center',
  },
  unreadDot: {
    position: 'absolute',
    top: -4,
    right: -4,
    minWidth: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: '#ef4444',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 3,
    borderWidth: 1.5,
    borderColor: '#fff',
  },
  unreadDotText: {
    color: '#fff',
    fontSize: 9,
    fontWeight: '800',
  },
  actionHint: {
    paddingHorizontal: 20,
    marginTop: 6,
    marginBottom: 8,
    fontSize: 11,
    color: '#94a3b8',
    fontWeight: '600',
  },
  tlRow: {
    flexDirection: 'row',
    minHeight: 44,
  },
  tlRail: {
    width: 22,
    alignItems: 'center',
  },
  tlDot: {
    width: 18,
    height: 18,
    borderRadius: 9,
    borderWidth: 2,
    borderColor: '#cbd5e1',
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  tlDotDone: {
    backgroundColor: TEAL,
    borderColor: TEAL,
  },
  tlDotCurrent: {
    borderColor: TEAL,
    borderWidth: 3,
    backgroundColor: '#fff',
  },
  tlLine: {
    width: 2,
    flex: 1,
    backgroundColor: '#e2e8f0',
    marginVertical: 2,
  },
  tlLineDone: {
    backgroundColor: TEAL,
  },
  tlBody: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    paddingBottom: 16,
    paddingLeft: 10,
  },
  tlLabel: {
    fontSize: 14,
    fontWeight: '700',
    color: '#64748b',
  },
  tlLabelCurrent: {
    color: TEAL,
  },
  tlTime: {
    fontSize: 12,
    color: '#94a3b8',
    fontWeight: '600',
  },
  miniCard: {
    backgroundColor: PAGE_BG,
    borderRadius: 12,
    padding: 12,
    marginBottom: 10,
  },
  miniCardTitle: {
    fontSize: 12,
    fontWeight: '800',
    color: '#64748b',
    marginBottom: 4,
  },
  miniCardText: {
    fontSize: 14,
    fontWeight: '700',
    color: NAVY,
  },
  miniCardMuted: {
    marginTop: 4,
    fontSize: 12,
    color: '#64748b',
  },
  summaryBar: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderTopWidth: 1,
    borderTopColor: '#eef2f6',
    gap: 10,
  },
  summaryThumb: {
    width: 44,
    height: 44,
    borderRadius: 10,
    backgroundColor: '#e8f5f6',
    alignItems: 'center',
    justifyContent: 'center',
  },
  summaryName: {
    flex: 1,
    fontSize: 14,
    fontWeight: '700',
    color: NAVY,
  },
  summaryPrice: {
    fontSize: 15,
    fontWeight: '800',
    color: NAVY,
  },
});
