import { pickCopy } from '../../i18n';

const TRACK_ORDER_COPY = {
  zh: {
    title: '追踪订单',
    subtitle: '输入订单号、快递单号或入库单号查询',
    inputPlaceholder: '订单号 / 快递单号 / 入库单号',
    crossBorderBadge: '跨境物流',
    inboundBarcode: '入库单号',
    expressBarcode: '快递单号',
    destination: '目的地',
    productName: '商品',
    trackButton: '查询',
    scanButton: '扫码查询',
    notFound: '未找到订单',
    notFoundDesc: '请检查订单号是否正确',
    orderInfo: '订单信息',
    orderNumber: '订单号',
    status: '当前状态',
    packageType: '包裹类型',
    weight: '重量',
    price: '价格',
    courier: '配送员',
    distance: '配送距离',
    senderInfo: '寄件信息',
    sender: '寄件人',
    senderPhone: '联系电话',
    senderAddress: '寄件地址',
    receiverInfo: '收件信息',
    receiver: '收件人',
    receiverPhone: '联系电话',
    receiverAddress: '收件地址',
    trackingHistory: '追踪历史',
    noHistory: '暂无追踪记录',
    createdAt: '下单时间',
    pickedUpAt: '取件时间',
    deliveredAt: '送达时间',
    inputError: '请输入订单号',
    searchError: '查询失败',
    searching: '查询中...',
    ongoingOrders: '未完成订单',
    tapToTrack: '点击立即追踪',
    offlineSearch: '当前网络不可用，请连接网络后再查询',
    offlineBanner: '当前处于离线状态，地图与实时追踪不可用',
    mapOfflineTitle: '网络不可用',
    mapOfflineDesc: '已为您保留订单详情，联网后可查看实时地图',
    mapErrorTitle: '地图加载失败',
    mapErrorDesc: '请稍后重试或检查网络与定位权限',
    chatWithCourier: '联系骑手',
    callCourier: '电话联系',
    messageCourier: '发送消息',
    customerService: '客服',
    etaMinutes: '预计 {n} 分钟送达',
    etaByOption: '按配送选项送达',
    riderDelivering: '骑手正在配送',
    noCourierPhone: '暂无骑手电话',
    stepPlaced: '已下单',
    stepPreparing: '商家备货',
    stepPicked: '骑手取货',
    stepDelivering: '正在配送',
    stepArrive: '待送达',
    stepArrived: '已送达',
    moreItems: '等',
    itemsUnit: '件',
    inputMessage: '输入消息...',
    sendMessage: '发送',
    noMessages: '暂无消息',
  },
  en: {
    title: 'Track Order',
    subtitle: 'Order ID, express waybill, or inbound barcode',
    inputPlaceholder: 'Order / express / inbound barcode',
    crossBorderBadge: 'Cross-border',
    inboundBarcode: 'Inbound barcode',
    expressBarcode: 'Express waybill',
    destination: 'Destination',
    productName: 'Product',
    trackButton: 'Track',
    scanButton: 'Scan',
    notFound: 'Order Not Found',
    notFoundDesc: 'Please check the order number',
    orderInfo: 'Order Information',
    orderNumber: 'Order No.',
    status: 'Status',
    packageType: 'Type',
    weight: 'Weight',
    price: 'Price',
    courier: 'Courier',
    distance: 'Distance',
    senderInfo: 'Sender',
    sender: 'Name',
    senderPhone: 'Phone',
    senderAddress: 'Address',
    receiverInfo: 'Receiver',
    receiver: 'Name',
    receiverPhone: 'Phone',
    receiverAddress: 'Address',
    trackingHistory: 'Tracking History',
    noHistory: 'No tracking records',
    createdAt: 'Created',
    pickedUpAt: 'Picked Up',
    deliveredAt: 'Delivered',
    inputError: 'Please enter order number',
    searchError: 'Search failed',
    searching: 'Searching...',
    ongoingOrders: 'Unfinished Orders',
    tapToTrack: 'Tap to track live',
    offlineSearch: 'You are offline. Please connect to the network to search.',
    offlineBanner: 'You are offline. Map and live tracking are unavailable.',
    mapOfflineTitle: 'Offline',
    mapOfflineDesc: 'Order details are available; live map will resume when online.',
    mapErrorTitle: 'Map failed to load',
    mapErrorDesc: 'Please try again later or check network and location permissions.',
    chatWithCourier: 'Chat with Courier',
    callCourier: 'Call',
    messageCourier: 'Message',
    customerService: 'Support',
    etaMinutes: 'ETA {n} min',
    etaByOption: 'By delivery option',
    riderDelivering: 'Rider is delivering',
    noCourierPhone: 'Courier phone unavailable',
    stepPlaced: 'Placed',
    stepPreparing: 'Preparing',
    stepPicked: 'Picked up',
    stepDelivering: 'Delivering',
    stepArrive: 'Out for delivery',
    stepArrived: 'Delivered',
    moreItems: '',
    itemsUnit: 'items',
    inputMessage: 'Type a message...',
    sendMessage: 'Send',
    noMessages: 'No messages yet',
  },
  my: {
    title: 'အော်ဒါခြေရာခံ',
    subtitle: 'အော်ဒါ / express / inbound barcode',
    inputPlaceholder: 'အော်ဒါ / express / inbound',
    crossBorderBadge: 'နယ်စပ်ဖြတ်ကျော်',
    inboundBarcode: 'ဂိုဒေါင်ဝင်ကုဒ်',
    expressBarcode: 'အမြန်ပို့ကုဒ်',
    destination: 'ဦးတည်ရာ',
    productName: 'ကုန်ပစ္စည်း',
    trackButton: 'ရှာဖွေ',
    scanButton: 'စကန်ဖတ်',
    notFound: 'အော်ဒါမတွေ့ပါ',
    notFoundDesc: 'အော်ဒါနံပါတ်ကိုစစ်ဆေးပါ',
    orderInfo: 'အော်ဒါအချက်အလက်',
    orderNumber: 'အော်ဒါနံပါတ်',
    status: 'အခြေအနေ',
    packageType: 'အမျိုးအစား',
    weight: 'အလေးချိန်',
    price: 'စျေးနှုန်း',
    courier: 'ပို့ဆောင်သူ',
    distance: 'အကွာအဝေး',
    senderInfo: 'ပို့သူ',
    sender: 'အမည်',
    senderPhone: 'ဖုန်း',
    senderAddress: 'လိပ်စာ',
    receiverInfo: 'လက်ခံသူ',
    receiver: 'အမည်',
    receiverPhone: 'ဖုန်း',
    receiverAddress: 'လိပ်စာ',
    trackingHistory: 'ခြေရာခံမှတ်တမ်း',
    noHistory: 'မှတ်တမ်းမရှိ',
    createdAt: 'ဖန်တီးချိန်',
    pickedUpAt: 'ထုတ်ယူချိန်',
    deliveredAt: 'ပို့ဆောင်ချိန်',
    inputError: 'အော်ဒါနံပါတ်ထည့်ပါ',
    searchError: 'ရှာဖွေမှုမအောင်မြင်',
    searching: 'ရှာဖွေနေသည်...',
    ongoingOrders: 'မပြီးသေးသော အော်ဒါများ',
    tapToTrack: 'တိုက်ရိုက်ခြေရာခံရန် နှိပ်ပါ',
    offlineSearch: 'အင်တာနက်မရှိပါ၊ ချိတ်ဆက်ပြီးမှ ရှာဖွေပါ',
    offlineBanner: 'အင်တာနက်မရှိပါ၊ မြေပုံနှင့် တိုက်ရိုက်ခြေရာခံမှုမရနိုင်ပါ',
    mapOfflineTitle: 'အင်တာနက်မရှိပါ',
    mapOfflineDesc: 'အော်ဒါအသေးစိတ်ပြန်လည်ကြည့်နိုင်ပြီး အင်တာနက်ရသောအခါ မြေပုံမြင်နိုင်သည်',
    mapErrorTitle: 'မြေပုံမရပါ',
    mapErrorDesc: 'ခဏနေရင် ထပ်ကြိုးစားပါ သို့မဟုတ် အင်တာနက်/တည်နေရာခွင့်ပြုမှုစစ်ဆေးပါ',
    chatWithCourier: 'ပို့ဆောင်သူနှင့် စကားပြောရန်',
    callCourier: 'ခေါ်ဆိုရန်',
    messageCourier: 'မက်ဆေ့ခ်ျ',
    customerService: 'ဝန်ဆောင်မှု',
    etaMinutes: '{n} မိနစ်ခန့်',
    etaByOption: 'ပို့ဆောင်မှု ရွေးချယ်မှုအတိုင်း',
    riderDelivering: 'ပို့ဆောင်နေသည်',
    noCourierPhone: 'ဖုန်းမရှိပါ',
    stepPlaced: 'မှာယူပြီး',
    stepPreparing: 'ပြင်ဆင်နေ',
    stepPicked: 'ယူပြီး',
    stepDelivering: 'ပို့ဆောင်နေ',
    stepArrive: 'ပို့ဆောင်ရန်',
    stepArrived: 'ပို့ပြီး',
    moreItems: '',
    itemsUnit: 'ခု',
    inputMessage: 'မက်ဆေ့ခ်ျရိုက်ပါ...',
    sendMessage: 'ပို့မည်',
    noMessages: 'မက်ဆေ့ခ်ျမရှိပါ',
  },
};

export function getTrackOrderCopy(language: string) {
  return pickCopy(language, TRACK_ORDER_COPY as { zh: any; en: any; my: any });
}
