import { StyleSheet, Dimensions, Platform } from 'react-native';

const { width, height } = Dimensions.get('window');

export const mapScreenStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#f8fafc' },
  header: {
    backgroundColor: '#1e293b', 
    paddingTop: Platform.OS === 'ios' ? 60 : 40, 
    paddingBottom: 15, 
    paddingHorizontal: 20,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 10,
    elevation: 5,
  },
  headerTitle: { color: '#fff', fontSize: 18, fontWeight: '800', letterSpacing: 0.5 },
  newOrderBannerWrap: {
    marginHorizontal: 16,
    marginBottom: 8,
    borderRadius: 14,
    overflow: 'hidden',
    elevation: 6,
    shadowColor: '#059669',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.35,
    shadowRadius: 8,
  },
  newOrderBannerInner: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 14,
  },
  newOrderBannerTextCol: {
    flex: 1,
    marginLeft: 10,
  },
  newOrderBannerTitle: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '800',
  },
  newOrderBannerId: {
    color: 'rgba(255,255,255,0.92)',
    fontSize: 13,
    fontWeight: '600',
    marginTop: 2,
    letterSpacing: 0.5,
  },
  newOrderBannerBtn: {
    backgroundColor: 'rgba(255,255,255,0.25)',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
    marginRight: 8,
  },
  newOrderBannerBtnText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '700',
  },
  statusBanner: { backgroundColor: '#fef3c7', padding: 12, margin: 16, borderRadius: 12, flexDirection: 'row', alignItems: 'center', borderLeftWidth: 4, borderLeftColor: '#f59e0b' },
  statusBannerOffline: { backgroundColor: '#fee2e2', borderLeftColor: '#ef4444' },
  statusBannerText: { fontSize: 13, color: '#92400e', flex: 1, fontWeight: '500' },
  retryButton: { backgroundColor: '#3b82f6', paddingHorizontal: 15, paddingVertical: 8, borderRadius: 8, marginLeft: 10 },
  retryButtonText: { color: '#fff', fontSize: 12, fontWeight: '700' },
  lastUpdateContainer: { paddingHorizontal: 16, paddingVertical: 10, backgroundColor: '#fff', alignItems: 'center', borderBottomWidth: 1, borderBottomColor: '#f1f5f9' },
  lastUpdateText: { fontSize: 12, color: '#64748b', fontWeight: '500' },
  listContainer: { flex: 1, paddingTop: 10 },
  searchFilterContainer: { flexDirection: 'row', paddingHorizontal: 16, paddingBottom: 12, gap: 10 },
  searchContainer: { 
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff', 
    borderRadius: 12, 
    paddingHorizontal: 12, 
    height: 46,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 2,
  },
  searchIcon: { fontSize: 16, marginRight: 8, opacity: 0.6 },
  searchInput: { flex: 1, fontSize: 14, color: '#1e293b', fontWeight: '500' },
  filterButton: { 
    backgroundColor: '#fff', 
    paddingHorizontal: 15, 
    height: 46, 
    justifyContent: 'center', 
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 2,
  },
  filterButtonText: { color: '#3b82f6', fontSize: 13, fontWeight: '700' },
  
  // 包裹卡片
  packageCard: {
    backgroundColor: '#fff',
    marginHorizontal: 16, 
    marginBottom: 12, 
    borderRadius: 16, 
    padding: 16, 
    shadowColor: '#000',
    shadowOpacity: 0.08, 
    shadowRadius: 12, 
    elevation: 4,
    borderWidth: 1,
    borderColor: '#f1f5f9'
  },
  currentDeliveringCard: { 
    borderColor: '#10b981',
    borderWidth: 2,
    backgroundColor: '#f0fdf4'
  },
  approachingPickupCard: {
    borderColor: '#f59e0b',
    borderWidth: 2,
    backgroundColor: '#fffbeb',
  },
  approachingDeliveryCard: {
    borderColor: '#3b82f6',
    borderWidth: 2,
    backgroundColor: '#eff6ff',
  },
  approachingPickupChip: {
    backgroundColor: '#fef3c7',
  },
  approachingDeliveryChip: {
    backgroundColor: '#dbeafe',
  },
  packageInfo: { gap: 12 },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9'
  },
  idGroup: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    flex: 1,
    flexWrap: 'wrap',
  },
  speedBadgeColumn: {
    flexShrink: 1,
    maxWidth: '56%',
  },
  scheduledTimeUnderBadge: {
    marginTop: 5,
    fontSize: 11,
    fontWeight: '800',
    color: '#b45309',
    lineHeight: 15,
  },
  packageId: { fontSize: 15, fontWeight: '800', color: '#1e293b' },
  speedBadge: { 
    flexDirection: 'row', 
    backgroundColor: '#f1f5f9', 
    paddingHorizontal: 8,
    paddingVertical: 3, 
    borderRadius: 8, 
    alignItems: 'center', 
    gap: 4 
  },
  speedIcon: { fontSize: 12 },
  speedText: { fontSize: 11, fontWeight: '700', color: '#475569' },
  deliveringBadge: { 
    flexDirection: 'row',
    backgroundColor: '#d1fae5', 
    paddingHorizontal: 10, 
    paddingVertical: 4, 
    borderRadius: 20, 
    alignItems: 'center',
    gap: 4
  },
  deliveringText: { fontSize: 11, fontWeight: '800', color: '#059669' },
  
  cardBody: {
    gap: 4
  },
  pickupSection: { flexDirection: 'row', gap: 12 },
  deliverySection: { flexDirection: 'row', gap: 12 },
  pointIndicator: {
    alignItems: 'center',
    width: 12,
    paddingTop: 6
  },
  pointDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
  },
  pointLine: {
    width: 2,
    flex: 1,
    backgroundColor: '#e2e8f0',
    marginVertical: 4,
    minHeight: 20
  },
  pointContent: {
    flex: 1,
    paddingBottom: 10
  },
  sectionTitle: { fontSize: 11, fontWeight: '700', color: '#94a3b8', marginBottom: 2, textTransform: 'uppercase' },
  senderName: { fontSize: 14, fontWeight: '700', color: '#1e293b', marginBottom: 2 },
  receiverName: { fontSize: 14, fontWeight: '700', color: '#1e293b', marginBottom: 2 },
  address: { fontSize: 12, color: '#64748b', lineHeight: 18 },
  
  actionRow: {
    flexDirection: 'row',
    gap: 12, 
    marginTop: 4,
    alignItems: 'center'
  },
  numberBadge: { 
    width: 28, 
    height: 28, 
    borderRadius: 14, 
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2
  },
  numberText: { color: '#fff', fontSize: 13, fontWeight: '800' },
  buttonGroup: {
    flex: 1,
  },
  dualButtons: {
    flexDirection: 'row',
    gap: 10
  },
  startDeliveryButton: {
    backgroundColor: '#10b981',
    height: 44,
    borderRadius: 12, 
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#10b981',
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 3
  },
  startDeliveryText: { color: '#fff', fontWeight: '800', fontSize: 14 },
  finishDeliveryButton: {
    backgroundColor: '#ef4444',
    height: 44,
    borderRadius: 12, 
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#ef4444',
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 3
  },
  finishDeliveryText: { color: '#fff', fontWeight: '800', fontSize: 14 },
  placeholderButton: { 
    flex: 1,
    height: 44,
    borderRadius: 12, 
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2
  },
  placeholderText: { color: '#fff', fontWeight: '800', fontSize: 13 },
  completedButton: { 
    height: 44,
    borderRadius: 12, 
    backgroundColor: '#f1f5f9', 
    alignItems: 'center',
    justifyContent: 'center'
  },
  completedText: { color: '#94a3b8', fontWeight: '800', fontSize: 14 },

  // 地图Modal
  mapModalContainer: { flex: 1, backgroundColor: '#fff' },
  mapModalHeader: {
    flexDirection: 'row',
    paddingHorizontal: 20, 
    paddingTop: Platform.OS === 'ios' ? 60 : 40, 
    paddingBottom: 20,
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#1e293b'
  },
  mapModalTitle: { color: '#fff', fontSize: 18, fontWeight: '800' },
  closeButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255,255,255,0.15)', 
    alignItems: 'center',
    justifyContent: 'center' 
  },
  mapPausedContainer: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: '#0f172a',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  mapPausedText: {
    color: '#e2e8f0',
    fontSize: 14,
    textAlign: 'center',
    fontWeight: '600',
  },
  courierMarker: {
    backgroundColor: '#10b981', 
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 3,
    borderColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 5
  },
  courierMarkerText: { fontSize: 20 },
  pickupMarker: { 
    backgroundColor: '#f59e0b', 
    width: 34, 
    height: 34, 
    borderRadius: 17, 
    alignItems: 'center',
    justifyContent: 'center', 
    borderWidth: 3,
    borderColor: '#fff',
    shadowColor: '#000',
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 4
  },
  packageMarker: { 
    backgroundColor: '#3b82f6', 
    width: 34, 
    height: 34, 
    borderRadius: 17, 
    alignItems: 'center',
    justifyContent: 'center', 
    borderWidth: 3,
    borderColor: '#fff',
    shadowColor: '#000',
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 4
  },
  pickupMarkerText: { color: '#fff', fontWeight: '900', fontSize: 13 },
  routePreviewMarkerAnchor: {
    alignItems: 'center',
  },
  routePreviewPickupPill: {
    backgroundColor: '#f59e0b',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: '#fff',
    maxWidth: width * 0.42,
    marginBottom: 4,
    shadowColor: '#000',
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 4,
  },
  routePreviewDeliveryPill: {
    backgroundColor: '#2563eb',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: '#fff',
    maxWidth: width * 0.42,
    marginBottom: 4,
    shadowColor: '#000',
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 4,
  },
  routePreviewPillText: {
    color: '#fff',
    fontWeight: '900',
    fontSize: 11,
  },
  routePreviewPickupDot: {
    width: 14,
    height: 14,
    borderRadius: 7,
    backgroundColor: '#f59e0b',
    borderWidth: 2,
    borderColor: '#fff',
  },
  routePreviewDeliveryDot: {
    width: 14,
    height: 14,
    borderRadius: 7,
    backgroundColor: '#2563eb',
    borderWidth: 2,
    borderColor: '#fff',
  },
  routeListContainer: { 
    position: 'absolute', 
    bottom: 0, 
    left: 0, 
    right: 0, 
    height: 320, 
    backgroundColor: 'rgba(255,255,255,0.98)', 
    borderTopLeftRadius: 30, 
    borderTopRightRadius: 30, 
    padding: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 10
  },
  routeListHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 15 },
  routeListTitle: { fontSize: 17, fontWeight: '800', color: '#1e293b' },
  startNavigationButtonCompact: { borderRadius: 14, overflow: 'hidden' },
  navBtnGradientSmall: { paddingHorizontal: 20, paddingVertical: 10 },
  navBtnTextSmall: { color: '#fff', fontWeight: '800', fontSize: 14 },
  routeListScroll: { flex: 1 },
  routeListItem: { 
    backgroundColor: '#f8fafc', 
    borderRadius: 16,
    borderWidth: 1, 
    borderColor: '#f1f5f9',
    padding: 12,
    marginBottom: 10
  },
  routeNumberBadgeCompact: { 
    width: 26, 
    height: 26, 
    borderRadius: 13, 
    backgroundColor: '#1e293b', 
    alignItems: 'center',
    justifyContent: 'center' 
  },
  routeNumberBadgeTextCompact: { color: '#fff', fontSize: 12, fontWeight: '800' },
  statusDot: { width: 10, height: 10, borderRadius: 5 },
  
  cameraModalContainer: { flex: 1, backgroundColor: 'rgba(0,0,0,0.6)', justifyContent: 'center', padding: 24 },
  cameraModalContent: { backgroundColor: '#fff', borderRadius: 24, padding: 24, shadowColor: '#000', shadowOpacity: 0.2, shadowRadius: 15, elevation: 10 },
  cameraModalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 24 },
  cameraModalTitle: { fontSize: 20, fontWeight: '800', color: '#1e293b' },
  cameraModalBody: { alignItems: 'center' },
  cameraButton: { backgroundColor: '#10b981', width: '100%', padding: 18, borderRadius: 16, alignItems: 'center', shadowColor: '#10b981', shadowOpacity: 0.3, shadowRadius: 10, elevation: 5 },
  cameraButtonText: { color: '#fff', fontWeight: '800', fontSize: 16 },
  
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.85)', justifyContent: 'center', alignItems: 'center', padding: 20 },
  glassModal: { width: '100%', backgroundColor: 'rgba(30, 41, 59, 0.98)', borderRadius: 32, borderWidth: 1, borderColor: 'rgba(255,255,255,0.1)', overflow: 'hidden' },
  modalHeader: { padding: 24, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', borderBottomWidth: 1, borderBottomColor: 'rgba(255,255,255,0.05)' },
  modalTitle: { color: '#fff', fontSize: 18, fontWeight: '800' },
  modalBody: { padding: 24 },
  closeBtn: { width: 36, height: 36, borderRadius: 18, backgroundColor: 'rgba(255,255,255,0.05)', justifyContent: 'center', alignItems: 'center' },
  disabledBtn: { opacity: 0.5 },
  gridActionBtn: { flex: 1, height: 100, borderRadius: 20, overflow: 'hidden' },
  gridBtnGradient: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  gridBtnText: { color: '#fff', fontSize: 12, fontWeight: '800', marginTop: 10 },
  
  photoModalContainer: { flex: 1, backgroundColor: '#000', justifyContent: 'center' },
  photoModalContent: { flex: 1, backgroundColor: '#fff', marginTop: 60, borderTopLeftRadius: 30, borderTopRightRadius: 30, padding: 24 },
  photoModalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20 },
  photoModalTitle: { fontSize: 20, fontWeight: '800', color: '#1e293b' },
  photoModalBody: { flex: 1 },
  photoPreviewWrapper: { width: '100%', flex: 1, borderRadius: 20, marginBottom: 24, backgroundColor: '#f1f5f9', overflow: 'hidden' },
  uploadButton: { borderRadius: 16, overflow: 'hidden', marginBottom: 20 },
  uploadButtonGradient: { padding: 18, alignItems: 'center', justifyContent: 'center' },
  uploadButtonText: { color: '#fff', fontWeight: '800', fontSize: 16 },
  
  pointNavAction: { 
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6, 
    backgroundColor: '#eff6ff', 
    paddingHorizontal: 10, 
    paddingVertical: 6, 
    borderRadius: 8,
    alignSelf: 'flex-start',
    marginTop: 4
  },
  pointNavActionText: { color: '#3b82f6', fontSize: 12, fontWeight: '800' },
  emptyContainer: { flex: 1, justifyContent: 'center', alignItems: 'center', padding: 40 },
  emptyEmoji: { fontSize: 70, marginBottom: 24 },
  emptyTitle: { fontSize: 20, fontWeight: '800', color: '#475569', marginBottom: 12 },
  refreshButton: { backgroundColor: '#3b82f6', paddingHorizontal: 30, paddingVertical: 14, borderRadius: 16, shadowColor: '#3b82f6', shadowOpacity: 0.3, shadowRadius: 10, elevation: 5 },
  refreshButtonText: { color: '#fff', fontWeight: '800', fontSize: 16 },
  identityBadge: {
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 6,
  },
  identityText: {
    color: '#fff',
    fontSize: 10,
    fontWeight: '800',
  },
  scheduledDeliveryModalStrip: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: '#fffbeb',
    borderBottomWidth: 1,
    borderBottomColor: '#fde68a',
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  scheduledDeliveryModalStripLabel: {
    fontSize: 11,
    fontWeight: '800',
    color: '#92400e',
    marginBottom: 2,
  },
  scheduledDeliveryModalStripValue: {
    fontSize: 13,
    fontWeight: '700',
    color: '#78350f',
  },
  merchantCodBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fef2f2',
    borderWidth: 1.5,
    borderColor: '#fecaca',
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 12,
    marginTop: 8,
  },
  merchantCodBannerTitle: {
    color: '#991b1b',
    fontSize: 12,
    fontWeight: '800',
  },
  merchantCodBannerAmount: {
    color: '#b91c1c',
    fontSize: 17,
    fontWeight: '900',
    marginTop: 2,
  },
  merchantCodInline: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 4,
  },
  merchantCodInlineTextMuted: {
    color: '#64748b',
    fontSize: 11,
    fontWeight: '700',
  },
});
