import { pickCopy } from '../../i18n';

const PLACE_ORDER_COPY = {
  zh: {
    title: '立即下单',
    subtitle: '请填写订单信息',
    wizardSteps: ['地址', '包裹', '配送', '确认'],
    wizardNext: '下一步',
    wizardBack: '上一步',
    wizardExit: '退出',
    guestLoginToSubmit: '登录后即可提交订单',
    senderInfo: '寄件人信息',
    useMyInfo: '使用我的信息',
    senderName: '寄件人姓名',
    senderPhone: '寄件人电话',
    senderAddress: '取件地址',
    useCurrentLocation: '使用当前位置',
    openMap: '打开地图',
    receiverInfo: '收件人信息',
    receiverName: '收件人姓名',
    receiverPhone: '收件人电话',
    receiverAddress: '送达地址',
    packageInfo: '包裹信息',
    packageType: '包裹类型',
    weight: '重量（kg）',
    description: '物品描述（选填）',
    codAmount: '代收款 (COD)',
    hasCOD: '代收状态',
    collect: '有代收',
    noCollect: '无代收',
    selectProduct: '选择商品',
    selectedProducts: '已选商品',
    totalProductPrice: '商品总价',
    deliveryOptions: '配送选项',
    deliveryByOption: '按配送选项送达',
    payableAmount: '应付金额',
    deliverySpeed: '配送速度',
    speedStandard: '准时达（1小时内）',
    speedExpress: '急送达（30分钟内）',
    speedScheduled: '定时达（指定时间）',
    speedWaySide: '顺路递（24小时内）',
    scheduledTime: '指定送达时间',
    priceEstimate: '预估价格',
    distance: '配送距离',
    basePrice: '起步价',
    distancePrice: '里程费',
    speedPrice: '时效费',
    totalPrice: '总计',
    calculateButton: '计算',
    priceEstimateAutoHint: '填写地址、包裹与配送选项后将自动显示费用',
    priceEstimateAutoSubtext: '超重/超规件请填写重量',
    calculating: '计算中...',
    calculateSuccess: '计算完成',
    calculateFailed: '计算失败',
    submitOrder: '提交订单',
    fillRequired: '请填写所有必填项',
    orderSuccess: '订单创建成功',
    orderFailed: '订单创建失败',
    creating: '正在创建订单...',
    kmUnit: '公里',
    orderNumber: '订单号',
    totalAmount: '总金额',
    paidAmount: '实付金额',
    productAmount: '商品金额',
    deliveryFee: '配送费',
    coupon: '优惠券',
    remarksOptional: '备注（选填）',
    noRemarks: '无',
    qrTitle: '订单已提交',
    qrHint: '请向骑手出示此二维码，用于取件扫描',
    saveQR: '保存二维码',
    qrClose: '关闭',
    viewOrders: '查看订单',
    continueOrder: '继续下单',
    kgUnit: '公斤',
    orderSavedOfflineTitle: '网络不稳定，已离线保存订单',
    orderSavedOfflineDescription: '我们会在网络恢复后自动同步，请勿重复提交。',
    orderSavedOfflineAction: '好的',
    placeholders: {
      name: '请输入姓名',
      phone: '请输入电话号码',
      address: '请输入详细地址',
      weight: '请输入重量',
      codAmount: '请输入代收款金额',
      description: '如：衣服、食品等',
      scheduledTime: '如：今天18:00',
    },
    paymentMethod: '支付方式',
    balancePayment: '余额支付',
    cashPayment: '现金支付',
    courierFeeBalance: '跑腿费 (余额支付)',
    courierFeeCash: '跑腿费 (现金支付)',
    shippingFeePayment: '跑腿费支付方式',
    itemBalancePayment: '商品费用 (仅余额支付)',
    accountBalance: '账户余额',
    insufficientBalance: '余额不足',
    itemsTotal: '商品总计',
    totalRequired: '总计费用',
    rechargeBeforeMall: '请先充值后再购买商场商品。',
    balanceDeducted: '支付成功，已从余额扣除',
    paymentMethodDesc: '请选择订单支付方式',
    useBalance: '优先使用余额支付',
    useCash: '使用现金支付',
    coordinates: '坐标',
    packageTypes: {
      document: '文件',
      standard: '标准件',
      overweight: '超重件',
      oversized: '超规件',
      fragile: '易碎品',
      foodDrinks: '食品和饮料',
      waySide: '顺路递',
    },
    packageTypeDetails: {
      standard: '标准件（45x60x15cm）和（5KG）以内',
      overweight: '超重件（5KG）以上',
      oversized: '超规件（45x60x15cm）以上',
      waySide: '顺路递 (24小时内送达)',
    },
    packageTypeInfo: {
      title: '包裹类型说明',
      sizeLimit: '尺寸限制',
      weightLimit: '重量限制',
      weightRequirement: '重量要求',
      sizeRequirement: '尺寸要求',
      description: '说明',
      standardDescription: '适用于常规大小的包裹，如衣物、文件、小型物品等。',
      overweightDescription: '适用于重量超过5公斤的包裹。重物品需要额外运费，请确保包装牢固。',
      oversizedDescription: '适用于尺寸超过标准的大型包裹。大件物品需要额外运费，请提前联系确认是否可以运输。',
      waySideDescription: '24小时顺路送达。最实惠的配送方式，不计距离和重量费。',
      understood: '我知道了',
    },
    timePicker: {
      title: '选择送达时间',
      subtitle: '请选择您期望的送达日期和时间',
      workingHours: '营业时间: 09:00 - 18:00',
      selectDate: '选择日期',
      selectTime: '选择时间',
      confirm: '确定',
      cancel: '取消',
      today: '今天',
      tomorrow: '明天',
    },
  },
  en: {
    title: 'Place Order',
    subtitle: 'Please fill in order information',
    wizardSteps: ['Address', 'Package', 'Delivery', 'Confirm'],
    wizardNext: 'Next',
    wizardBack: 'Back',
    wizardExit: 'Exit',
    guestLoginToSubmit: 'Sign in to submit your order',
    senderInfo: 'Sender Information',
    useMyInfo: 'Use my info',
    senderName: 'Sender Name',
    senderPhone: 'Sender Phone',
    senderAddress: 'Pickup Address',
    useCurrentLocation: 'Use current location',
    openMap: 'Open Map',
    receiverInfo: 'Receiver Information',
    receiverName: 'Receiver Name',
    receiverPhone: 'Receiver Phone',
    receiverAddress: 'Delivery Address',
    packageInfo: 'Package Information',
    packageType: 'Package Type',
    weight: 'Weight (kg)',
    description: 'Description (Optional)',
    codAmount: 'COD Amount',
    hasCOD: 'COD Status',
    collect: 'Collect',
    noCollect: 'No Collect',
    selectProduct: 'Select Products',
    selectedProducts: 'Selected',
    totalProductPrice: 'Total Price',
    deliveryOptions: 'Delivery Options',
    deliveryByOption: 'By delivery option',
    payableAmount: 'Amount due',
    deliverySpeed: 'Delivery Speed',
    speedStandard: 'Standard (within 1 hour)',
    speedExpress: 'Express (within 30 mins)',
    speedScheduled: 'Scheduled (specific time)',
    speedWaySide: 'Eco Way (within 24h)',
    scheduledTime: 'Scheduled Time',
    priceEstimate: 'Price Estimate',
    distance: 'Distance',
    basePrice: 'Base Price',
    distancePrice: 'Distance Fee',
    speedPrice: 'Speed Fee',
    totalPrice: 'Total',
    calculateButton: 'Calculate',
    priceEstimateAutoHint: 'Fee updates automatically when address, package and delivery are set',
    priceEstimateAutoSubtext: 'Enter weight for overweight/oversized items',
    calculating: 'Calculating...',
    calculateSuccess: 'Calculation Complete',
    calculateFailed: 'Calculation Failed',
    submitOrder: 'Submit Order',
    fillRequired: 'Please fill all required fields',
    orderSuccess: 'Order created successfully',
    orderFailed: 'Failed to create order',
    creating: 'Creating order...',
    kmUnit: 'km',
    orderNumber: 'Order Number',
    totalAmount: 'Total Amount',
    paidAmount: 'Amount paid',
    productAmount: 'Item amount',
    deliveryFee: 'Delivery fee',
    coupon: 'Coupon',
    remarksOptional: 'Notes (optional)',
    noRemarks: 'None',
    qrTitle: 'Order submitted',
    qrHint: 'Show this QR code to the courier for pickup',
    saveQR: 'Save QR code',
    qrClose: 'Close',
    viewOrders: 'View Orders',
    continueOrder: 'Continue Ordering',
    kgUnit: 'kg',
    orderSavedOfflineTitle: 'Order saved offline',
    orderSavedOfflineDescription: 'We stored this order locally and will sync it automatically once the network recovers. Please do not submit again.',
    orderSavedOfflineAction: 'Got it',
    placeholders: {
      name: 'Enter name',
      phone: 'Enter phone number',
      address: 'Enter detailed address',
      weight: 'Enter weight',
      codAmount: 'Enter COD amount',
      description: 'e.g.: Clothes, Food, etc.',
      scheduledTime: 'e.g.: Today 18:00',
    },
    paymentMethod: 'Payment Method',
    balancePayment: 'Balance Payment',
    cashPayment: 'Cash Payment',
    courierFeeBalance: 'Courier Fee (Balance Pay)',
    courierFeeCash: 'Courier Fee (Cash Pay)',
    shippingFeePayment: 'Shipping Fee Payment',
    itemBalancePayment: 'Item Cost (Balance Only)',
    accountBalance: 'Account Balance',
    insufficientBalance: 'Insufficient Balance',
    itemsTotal: 'Items Total',
    totalRequired: 'Total Required',
    rechargeBeforeMall: 'Please recharge before buying mall items.',
    balanceDeducted: 'Payment successful, deducted from balance',
    paymentMethodDesc: 'Please select a payment method',
    useBalance: 'Pay with Balance',
    useCash: 'Pay with Cash',
    coordinates: 'Coordinates',
    packageTypes: {
      document: 'Document',
      standard: 'Standard Package',
      overweight: 'Overweight',
      oversized: 'Oversized',
      fragile: 'Fragile',
      foodDrinks: 'Food & Drinks',
      waySide: 'Eco Way',
    },
    packageTypeDetails: {
      standard: 'Standard Package (45x60x15cm) and (5KG) or less',
      overweight: 'Overweight (over 5KG)',
      oversized: 'Oversized (over 45x60x15cm)',
      waySide: 'Eco Way (Within 24 Hours)',
    },
    packageTypeInfo: {
      title: 'Package Type Description',
      sizeLimit: 'Size Limit',
      weightLimit: 'Weight Limit',
      weightRequirement: 'Weight Requirement',
      sizeRequirement: 'Size Requirement',
      description: 'Description',
      standardDescription: 'Suitable for regular-sized packages such as clothing, documents, small items, etc.',
      overweightDescription: 'Suitable for packages weighing over 5KG. Heavy items require additional shipping fees. Please ensure secure packaging.',
      oversizedDescription: 'Suitable for large packages exceeding standard dimensions. Large items require additional shipping fees. Please contact in advance to confirm transportability.',
      waySideDescription: 'Delivery within 24 hours. Most affordable way, no distance or weight surcharge.',
      understood: 'I Understand',
    },
    timePicker: {
      title: 'Select Delivery Time',
      subtitle: 'Please select your preferred delivery date and time',
      workingHours: 'Working Hours: 09:00 - 18:00',
      selectDate: 'Select Date',
      selectTime: 'Select Time',
      confirm: 'Confirm',
      cancel: 'Cancel',
      today: 'Today',
      tomorrow: 'Tomorrow',
    },
  },
  my: {
    title: 'အမှာစာတင်',
    subtitle: 'အမှာစာအချက်အလက်ဖြည့်ပါ',
    wizardSteps: ['လိပ်စာ', 'ပါဆယ်', 'ပို့ဆောင်', 'အတည်ပြု'],
    wizardNext: 'ရှေ့သို့',
    wizardBack: 'နောက်သို့',
    wizardExit: 'ထွက်မည်',
    guestLoginToSubmit: 'အော်ဒါတင်ရန် ဝင်ရောက်ပါ',
    senderInfo: 'ပေးပို့သူအချက်အလက်',
    useMyInfo: 'ကျွန်ုပ်၏အချက်အလက်သုံးမည်',
    senderName: 'ပေးပို့သူအမည်',
    senderPhone: 'ပေးပို့သူဖုန်း',
    senderAddress: 'ယူရန်လိပ်စာ',
    useCurrentLocation: 'လက်ရှိတည်နေရာသုံးမည်',
    openMap: 'မြေပုံဖွင့်',
    receiverInfo: 'လက်ခံသူအချက်အလက်',
    receiverName: 'လက်ခံသူအမည်',
    receiverPhone: 'လက်ခံသူဖုန်း',
    receiverAddress: 'ပို့ရန်လိပ်စာ',
    packageInfo: 'ပါဆယ်အချက်အလက်',
    packageType: 'ပါဆယ်အမျိုးအစား',
    weight: 'အလေးချိန် (kg)',
    description: 'ပစ္စည်းဖော်ပြချက် (ရွေးချယ်)',
    codAmount: '代收款 (COD)',
    hasCOD: '代收状态',
    collect: 'ငွေကောက်ခံမည်',
    noCollect: 'ငွေမကောက်ခံပါ',
    deliveryOptions: 'ပို့ဆောင်ရေးရွေးချယ်မှု',
    deliveryByOption: 'ပို့ဆောင်မှု ရွေးချယ်မှုအတိုင်း',
    payableAmount: 'ပေးရမည့်ပမာဏ',
    deliverySpeed: 'ပို့ဆောင်မြန်နှုန်း',
    speedStandard: 'စံချိန် (၁နာရီအတွင်း)',
    speedExpress: 'အမြန် (၃၀မိနစ်အတွင်း)',
    speedScheduled: 'အချိန်သတ်မှတ် (သတ်မှတ်ထားသောအချိန်)',
    speedWaySide: 'တန်တန်လေးပို့ (၂၄ နာရီအတွင်း)',
    scheduledTime: 'သတ်မှတ်အချိန်',
    priceEstimate: 'ခန့်မှန်းစျေးနှုန်း',
    distance: 'အကွာအဝေး',
    basePrice: 'အခြေခံစျေးနှုန်း',
    distancePrice: 'အကွာအဝေးအခကြေး',
    speedPrice: 'မြန်နှုန်းအခကြေး',
    totalPrice: 'စုစုပေါင်း',
    calculateButton: 'တွက်ချက်မည်',
    priceEstimateAutoHint: 'လိပ်စာ၊ ပါဆယ်နှင့် ပို့ဆောင်ရွေးချယ်မှု ပြီးပါက အလိုအလျောက် ပြသပါမည်',
    priceEstimateAutoSubtext: 'အလေးချိန်ပိုပါဆယ် သို့မဟုတ် အရွယ်ပိုပါဆယ်အတွက် အလေးချိန်ကို ဖြည့်ပါ',
    calculating: 'တွက်ချက်နေသည်...',
    calculateSuccess: 'တွက်ချက်ပြီးပြီ',
    calculateFailed: 'တွက်ချက်မအောင်မြင်',
    submitOrder: 'အမှာစာတင်သွင်းမည်',
    fillRequired: 'လိုအပ်သောအကွက်များဖြည့်ပါ',
    orderSuccess: 'အမှာစာအောင်မြင်စွာဖန်တီးပြီး',
    orderFailed: 'အမှာစာဖန်တီးမှုမအောင်မြင်',
    selectedProducts: 'ကုန်ပစ္စည်းများ',
    creating: 'အမှာစာဖန်တီးနေသည်...',
    kmUnit: 'ကီလိုမီတာ',
    orderNumber: 'အမှာစာနံပါတ်',
    totalAmount: 'စုစုပေါင်းပမာဏ',
    paidAmount: 'ပေးပြီးပမာဏ',
    productAmount: 'ကုန်ပစ္စည်းပမာဏ',
    deliveryFee: 'ပို့ဆောင်ခ',
    coupon: 'ကူပွန်',
    remarksOptional: 'မှတ်ချက် (ရွေးချယ်)',
    noRemarks: 'မရှိပါ',
    qrTitle: 'အော်ဒါတင်ပြီးပါပြီ',
    qrHint: 'ပစ္စည်းယူသည့်အခါ ဤ QR ကုဒ်ကို စီးနင်းသူအား ပြပေးပါ',
    saveQR: 'QR ကုဒ်သိမ်းမည်',
    qrClose: 'ပိတ်မည်',
    viewOrders: 'အော်ဒါကြည့်ရန်',
    continueOrder: 'ဆက်လက်မှာယူမည်',
    kgUnit: 'ကီလိုဂရမ်',
    orderSavedOfflineTitle: 'အင်တာနက် မတော်တဆ ချိတ်ဆက်မရှိသဖြင့် အော်ဒါကို အော့ဖ်လိုင်း သိမ်းဆည်းထားပါသည်',
    orderSavedOfflineDescription: 'အင်တာနက် ပြန်လည်ရလာပါက အော်ဒါကို အလိုအလျောက် ပို့စ်ပေးမည်ဖြစ်ပြီး ထပ်မံတင်သွင်းရန် မလိုအပ်ပါ။',
    orderSavedOfflineAction: 'အိုကေ',
    placeholders: {
      name: 'အမည်ထည့်ပါ',
      phone: 'ဖုန်းနံပါတ်ထည့်ပါ',
      address: 'အသေးစိတ်လိပ်စာထည့်ပါ',
      weight: 'အလေးချိန်ထည့်ပါ',
      codAmount: '代收款 (COD) ပမာဏထည့်ပါ',
      description: 'ဥပမာ: အဝတ်အစား, အစားအစာ',
      scheduledTime: 'ဥပမာ: ယနေ့ ၁၈:၀၀',
    },
    paymentMethod: 'ပေးချေမှုနည်းလမ်း',
    balancePayment: 'လက်ကျန်ငွေဖြင့် ပေးချေခြင်း',
    cashPayment: 'ငွေသားဖြင့် ပေးချေခြင်း',
    courierFeeBalance: 'ပို့ဆောင်ခ (လက်ကျန်ငွေဖြင့်)',
    courierFeeCash: 'ပို့ဆောင်ခ (ငွေသားဖြင့်)',
    shippingFeePayment: 'ပို့ဆောင်ခ ပေးချေမှုနည်းလမ်း',
    itemBalancePayment: 'ကုန်ပစ္စည်းဖိုး (လက်ကျန်ငွေဖြင့်သာ)',
    accountBalance: 'အကောင့်လက်ကျန်ငွေ',
    insufficientBalance: 'လက်ကျန်ငွေမလုံလောက်ပါ',
    itemsTotal: 'ကုန်ပစ္စည်း စုစုပေါင်း',
    totalRequired: 'လိုအပ်သော စုစုပေါင်း',
    rechargeBeforeMall: 'ဈေးဝယ်ရန် အရင်ငွေဖြည့်ပါ။',
    balanceDeducted: 'ပေးချေမှုအောင်မြင်ပါသည်၊ လက်ကျန်ငွေမှ နုတ်ယူပြီးပါပြီ',
    paymentMethodDesc: 'ပေးချေမှုနည်းလမ်းကို ရွေးချယ်ပါ',
    useBalance: 'လက်ကျန်ငွေဖြင့် ပေးချေမည်',
    useCash: 'ငွေသားဖြင့် ပေးချေမည်',
    coordinates: 'ကိုဩဒိနိတ်',
    packageTypes: {
      document: 'စာရွက်စာတမ်း',
      standard: 'ပုံမှန်ပါဆယ်',
      overweight: 'အလေးချိန်ပိုပါဆယ်',
      oversized: 'အရွယ်အစားကြီးပါဆယ်',
      fragile: 'ကျိုးပဲ့လွယ်သောပစ္စည်း',
      foodDrinks: 'အစားအသောက်',
      waySide: 'တန်တန်လေးပို့',
    },
    packageTypeDetails: {
      standard: 'ပုံမှန်ပါဆယ် (45x60x15cm) နှင့် (5KG) အောက်',
      overweight: 'အလေးချိန်ပိုပါဆယ် (5KG အထက်)',
      oversized: 'အရွယ်အစားကြီးပါဆယ် (45x60x15cm အထက်)',
      waySide: 'တန်တန်လေးပို့ (၂၄ နာရီအတွင်း)',
    },
    packageTypeInfo: {
      title: 'ပါဆယ်အမျိုးအစားရှင်းလင်းချက်',
      sizeLimit: 'အရွယ်အစားကန့်သတ်ချက်',
      weightLimit: 'အလေးချိန်ကန့်သတ်ချက်',
      weightRequirement: 'အလေးချိန်လိုအပ်ချက်',
      sizeRequirement: 'အရွယ်အစားလိုအပ်ချက်',
      description: 'ရှင်းလင်းချက်',
      standardDescription: 'ပုံမှန်အရွယ်အစားရှိသောပါဆယ်များအတွက်သင့်လျော်သည်။ ဥပမာ: အဝတ်အစား၊ စာရွက်စာတမ်း၊ သေးငယ်သောပစ္စည်းများ။',
      overweightDescription: '၅ကီလိုဂရမ်ထက်ပိုလေးသောပါဆယ်များအတွက်သင့်လျော်သည်။ လေးသောပစ္စည်းများအတွက် အပိုပို့ဆောင်ခ လိုအပ်ပါသည်။ ထုပ်ပိုးမှုခိုင်မာစွာပြုလုပ်ပါ။',
      oversizedDescription: 'စံချိန်ထက်ကြီးသောအရွယ်အစားရှိသောပါဆယ်များအတွက်သင့်လျော်သည်။ ကြီးမားသောပစ္စည်းများအတွက် အပိုပို့ဆောင်ခ လိုအပ်ပါသည်။ ပို့ဆောင်နိုင်မနိုင်ကို ကြိုတင်ဆက်သွယ်ပါ။',
      waySideDescription: '၂၄ နာရီအတွင်း တန်တန်လေး ပို့ဆောင်ပေးပါသည်။ စျေးအသက်သာဆုံး ပို့ဆောင်မှုဖြစ်ပြီး အကွာအဝေးနှင့် အလေးချိန်ကြေး မကောက်ခံပါ။',
      understood: 'နားလည်ပါပြီ',
    },
    timePicker: {
      title: 'ပို့ဆောင်မည့်အချိန်ရွေးပါ',
      subtitle: 'သင်အလိုရှိသော ပို့ဆောင်မည့်ရက်နှင့် အချိန်ကို ရွေးချယ်ပါ',
      workingHours: 'ရုံးဖွင့်ချိန်: 09:00 - 18:00',
      selectDate: 'ရက်စွဲရွေးပါ',
      selectTime: 'အချိန်ရွေးပါ',
      confirm: 'အတည်ပြုသည်',
      cancel: 'ပယ်ဖျက်သည်',
      today: 'ယနေ့',
      tomorrow: 'မနက်ဖြန်',
    },
  },
};

export function getPlaceOrderCopy(language: string) {
  return pickCopy(language, PLACE_ORDER_COPY as { zh: any; en: any; my: any });
}

export type PlaceOrderCopy = ReturnType<typeof getPlaceOrderCopy>;
